### PR TITLE
Migrate to more recent SvelteKit

### PR DESCRIPTION
**Pull request by davej**
This is a follow-on from #67.

- [x] demo package has to be updated.
- [ ] links resolution is wrong as it's resolving named page routes (i.e., index.svelte instead of +page.svelte). This is mostly in the node/handlers/index.ts file.
- [x] The glob in sitemap.xml seems to not be picking up an files strangely.

@mihar-22 I'm not quite sure what you mean by "links resolution is wrong"? Could you give more detail and I can try to fix it.

### CODE REVIEW

**Comment by davej** [comment]
@mihar-22 These two functions already seem ok to me but I'm not 100% sure. Can you tell me if the input and output look correct below?

```js
resolveSlug("docs/getting-started/introduction")
// ->
"src/routes/docs/[...1]getting-started/[...1]introduction/+page.md"
```

```js
slugifyFilePath("/Users/davejeffery/code/forks/kit-docs/packages/kit-docs/src/routes/docs/[...4]production/[...6]deploying/+page.md")
// ->
"/docs/production/deploying"
```

**Comment by davej** [comment]
In my latest commit (d5daa84) I managed to get `http://localhost:3001/kit-docs/docs.sidebar.json` working when there is a `+page.md` file directly in the root of the `docs` directory. I did this just by following of execution when `http://localhost:3001/kit-docs/docs.sidebar.json` is requested. But this was a complete guess because I'm missing a lot of context about how this works.

It works for me now @mihar-22 but I'm not sure if it is correct and you are probably best placed to make the last couple of adjustments if they are needed.

**Comment by davej** [comment]
I am seeing the following error in the console. Any idea what might be going on here?

```
Error: Module "worker_threads" has been externalized for browser compatibility. Cannot access "worker_threads.resourceLimits" in client code.
```

**Comment by mihar-22** [comment]
> @mihar-22 These two functions already seem ok to me but I'm not 100% sure. Can you tell me if the input and output look correct below?

Looks good to me.

> It works for me now @mihar-22 but I'm not sure if it is correct and you are probably best placed to make the last couple of adjustments if they are needed.

Sure I'll walk through everything when you're done :)

> I am seeing the following error in the console. Any idea what might be going on here?

Unfortunately not, probably SvelteKit or Vite related.

**Comment by davej** [comment]
@mihar-22 Ah looks like @slowsage might have added a `workers_thread` import by mistake: https://github.com/svelteness/kit-docs/pull/68/files#diff-2bc97177721c228bd7d17f03d5e7e1690b82a0004f632782adf5c48c890a4d75R2

**Comment by davej** [comment]
Ok, @mihar-22, I'm finished now. This is ready for review.

**Comment by mihar-22** [comment]
Awesome thank you so much @davej! I'll have a look either today or tomorrow depending on my work.

**Comment by davej** [comment]
Thanks. I appreciate it. Looking forward to getting this merged! 😊

**Comment by mihar-22** [comment]
I think because this was forked from slowsage's fork I can't push to it. I created a new branch `pr/67` and with it a new PR.

https://github.com/svelteness/kit-docs/pull/69

**Pull request closed without merging**
