### PR TITLE
migrate to latest sveltekit

### PR DESCRIPTION
**Pull request by mihar-22**
Continuation of the work from @slowsage and @davej:

- https://github.com/svelteness/kit-docs/pull/67
- https://github.com/svelteness/kit-docs/pull/68

### CODE REVIEW

**Comment by mihar-22** [comment]
Only one issue remaining which is the Vite server keeps restarting on any file change. No idea why at the moment.

**Comment by joshnuss** [comment]
@mihar-22 Updating to `vite` `^4.0.0` seems to fix it for me.

**Comment by mihar-22** [comment]
Unforunately just tested that @joshnuss and it still fails. I'm getting the sense this might be a local only issue due to symlinks. I'm going to release and see how it goes for everyone.

**Comment by MarkyEasyGo** [comment]
Hey did we figure out a way past Vite server constantly refreshing and breaking local dev? Sadly I'm unable to run any combo locally, fresh installs and following instructions on docs page.

**Comment by mihar-22** [comment]
Unforunately not @MarkyEasyGo, I opened a new [issue issue](https://github.com/svelteness/kit-docs/issues/70).

**Pull request merged**
