### PR TITLE
fix: pin create-svelte version to avoid bug like #52

### PR DESCRIPTION
**Pull request by stephane-klein**
See https://github.com/svelteness/kit-docs/issues/52#issuecomment-1186494202

@mihar-22 what do you think about this Pull Request, to pin [`create-svelte`](https://github.com/sveltejs/kit/blob/0dd17945445661f04d11863ff0650910c1448248/packages/create-svelte/package.json#L3) version to avoid SvelteKit breaking changes.

### CODE REVIEW

**Comment by mihar-22** [comment]
I still don't think we should. Most the breaking changes where from the upgrade to Vite 3 which have cooled down now. I just missed the `$app` fix when I updated things before.

**Comment by stephane-klein** [comment]
>  I just missed the $app fix when I updated things before.

@mihar-22 I think you haven't missed `$app`, in your https://github.com/svelteness/kit-docs/commit/22d6a8350212c3aa2efc0b70cb29b219f16bed91 dated 2022-07-13, because the `SvelteKit` breaking change date 2022-07-14, after your fix :thinking:.

**Comment by stephane-klein** [comment]
@mihar-22 since 2 weeks, I think I have each day some breaking change. For now, I think it is not possible to use Kit-docs 😭

**Comment by mihar-22** [comment]
I'm sorry @stephane-klein. I'll have a look today to see if I can get everything working again.

**Pull request closed without merging**
