### PR TITLE
pnpm dev working

### PR DESCRIPTION
**Pull request by slowsage**
~~This is a best effort to migrate to the new routing system covering kit-docs (not the create module). I got the sidebar working and a lot of other small things. It may help you finish the integration. There are 3 unresolved issues:~~

1. ~~There is one issue with pnpm build - it needs the Response type in the node/handler.~~
2. ~~Run pnpm dev. There is a layout issue~~ fixed
3. ~~shiki config may need to be fixed for various languages.~~  Added languages manually. Not sure what the correct approach is.

I think I fixed all the major issues.
kit-docs package seems to be working.

Thank you

### CODE REVIEW

**Comment by mihar-22** [comment]
Oh wow, thank you so much @slowsage. I'll pull it down and have a quick look now.

**Comment by mihar-22** [comment]
It's an awesome start! Not much left to go:

- I updated `create` package to align with your changes. Need to test if it still works.
- `demo` package has to be updated.
- links resolution is wrong as it's resolving named page routes (i.e., `index.svelte` instead of `+page.svelte`).
- The glob in `sitemap.xml` seems to not be picking up an files strangely. 

I think that's about it, I'll have another look tonight and see what else I can add in. Thank you again slowsage.

**Comment by davej** [comment]
Followed on from this in #68. I would appreciate it if you take a look @mihar-22. Just one item remaining, if you give me some clarification then I should be able to fix that too.

**Comment by mihar-22** [comment]
I think because this was forked from slowsage's fork I can't push to it. I created a new branch `pr/67` and with it a new PR.

https://github.com/svelteness/kit-docs/pull/69

**Pull request closed without merging**
